# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyInstaller Windows

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write  # 需要发布权限
  
jobs:
  build-windows:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements and PyInstaller
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller
        run: |
          pyinstaller --name ExcelToCsv --onefile --console easy_xlsx_to_csv.py 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: dist/ExcelToCsv.exe  # 指定生成的 .exe 文件
          
      - name: Generate version tag
        id: get_version
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"  # 使用当前时间戳作为版本号
          echo "::set-output name=version::$VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/ExcelToCsv.exe
          tag_name: ${{ github.ref }}  # 使用 Git 标签作为版本号
          name: "v${{ steps.get_version.outputs.version }} Windows x64"  # 标注为 Windows x64 版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
